struct Node* makeNode(int data);
void displayLL(struct Node* head);
void insertAtBeginLL(struct Node** head, int data);
void insertAtEndLL(struct Node** head, int data);
void insertBeforeKLL(struct Node** head, int data, int k);
void insertAfterKLL(struct Node** head, int data, int k);
void insertAtILL(struct Node** head, int data, int pos);
void deleteAtBeginLL(struct Node** head);
void deleteAtEndLL(struct Node** head);
void deleteAtILL(struct Node** head, int pos);
void deleteValueKLL(struct Node** head, int k);
void searchLL(struct Node* head, int data);
void lengthLL(struct Node* head);
int operateLL();